server {
    server_name kwiddex.com www.kwiddex.com;

    root /home/vierbruno03/Draft-of-Kwiddex-Merged/frontend/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        limit_req zone=kwiddex_limit burst=20 nodelay;
        proxy_pass http://127.0.0.1:3001;
    }

    location /ml/ {
        proxy_pass http://127.0.0.1:8000;
    }

    
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header Referrer-Policy strict-origin-when-cross-origin;



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/kwiddex.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/kwiddex.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.kwiddex.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = kwiddex.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name kwiddex.com www.kwiddex.com;
    return 404; # managed by Certbot




}